/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CartPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProductPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProductScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/offers` | `/offers`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Homescreen`; params?: Router.UnknownInputParams; } | { pathname: `/utils/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/helper`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CartPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/offers` | `/offers`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProductList`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/Homescreen`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/helper`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CartPage${`?${string}` | `#${string}` | ''}` | `/ProductPage${`?${string}` | `#${string}` | ''}` | `/ProductScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/offers${`?${string}` | `#${string}` | ''}` | `/offers${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/ProductList${`?${string}` | `#${string}` | ''}` | `/src/screens/Homescreen${`?${string}` | `#${string}` | ''}` | `/utils/CartContext${`?${string}` | `#${string}` | ''}` | `/utils/helper${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CartPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProductPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProductScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/offers` | `/offers`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Homescreen`; params?: Router.UnknownInputParams; } | { pathname: `/utils/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/utils/helper`; params?: Router.UnknownInputParams; };
    }
  }
}
